#!/usr/bin/env python3
"""Decode pinned, hash-verified classic XPMs to a generated C++ header.

Only the format used by the pinned tool/graph assets is accepted. No host imaging
library or runtime XPM dependency; no scaling, palette replacement or redraw.
"""
import argparse
import hashlib
import json
from pathlib import Path
import re

def decode(path):
    rows=re.findall(r'^"(.*)"(?:,|};)?$',path.read_text(),re.M)
    w,h,n,cpp=map(int,rows[0].split())
    if not (0<w<=512 and 0<h<=4096 and cpp==1 and 0<n<=256 and len(rows)==1+n+h):
        raise ValueError(f'Unexpected XPM structure: {path}')
    palette={}
    for row in rows[1:n+1]:
        # Year selectors also specify an X11 monochrome fallback. RTG uses
        # the original color field; keep the source asset unchanged.
        match=re.fullmatch(r'(.).*?c #([0-9a-fA-F]{6}|[0-9a-fA-F]{12})(?: m #[0-9a-fA-F]{6})?',row)
        if not match: raise ValueError(f'Unexpected palette: {path}: {row}')
        value=match[2]
        if len(value)==12:
            value=''.join(f'{int(value[i:i+4],16)>>8:02x}' for i in range(0,12,4))
        palette[match[1]]=0xff000000|int(value,16)
    pixels=[]
    for row in rows[n+1:]:
        if len(row)!=w: raise ValueError(f'Wrong pixel row: {path}')
        pixels.extend(palette[c] for c in row)
    return w,h,pixels

def main():
    parser=argparse.ArgumentParser()
    parser.add_argument('output',type=Path)
    parser.add_argument('--family',choices=['tools','graphs','overview'],default='tools')
    args=parser.parse_args()
    assets=Path(__file__).resolve().parents[1]/('assets/classic-'+args.family)
    manifest=json.loads((assets/'source.json').read_text())
    if args.family=='overview':
        if len(manifest['files'])!=2: raise ValueError('Incomplete classic overview family')
        source=['// Generated by scripts/build-classic-art.py; original EA/Micropolis art.',
                '// See assets/classic-overview/COPYING and NOTICE.txt.',
                '#include <cstdint>',
                'struct ClassicOverviewArtImage {int width,height; const uint32_t *pixels;};']
        entries=[]
        for record in manifest['files']:
            path=assets/record['name']
            if hashlib.sha256(path.read_bytes()).hexdigest()!=record['sha256']:
                raise ValueError(f'Asset hash mismatch: {path}')
            w,h,pixels=decode(path)
            symbol='overview_'+path.stem
            source.append('static const uint32_t '+symbol+'[]={')
            source.extend(','.join(hex(p) for p in pixels[i:i+16])+',' for i in range(0,len(pixels),16))
            source.append('};')
            entries.append((path.stem,w,h,symbol))
        for name,w,h,symbol in entries:
            source.append('static const ClassicOverviewArtImage classic_'+name+'={'+f'{w},{h},{symbol}'+'};')
        args.output.parent.mkdir(parents=True,exist_ok=True)
        args.output.write_text('\n'.join(source)+'\n')
        print('classic-art: verified and decoded 2 pinned overview XPMs')
        return
    count=18 if args.family=='tools' else 8
    if len(manifest['files'])!=count*2: raise ValueError('Incomplete classic icon family')
    image_type='ClassicArtImage' if args.family=='tools' else 'ClassicGraphArtImage'
    table='classicArt' if args.family=='tools' else 'classicGraphArt'
    source=['// Generated by scripts/build-classic-art.py; original EA/Micropolis art.',
            '// See assets/classic-'+args.family+'/COPYING and NOTICE.txt.',
            '#include <cstdint>',
            'struct '+image_type+' {int width,height; const uint32_t *pixels;};']
    entries=[]
    for record in manifest['files']:
        path=assets/record['name']
        if hashlib.sha256(path.read_bytes()).hexdigest()!=record['sha256']:
            raise ValueError(f'Asset hash mismatch: {path}')
        w,h,pixels=decode(path)
        symbol='art_'+path.stem
        source.append('static const uint32_t '+symbol+'[]={')
        source.extend(','.join(hex(p) for p in pixels[i:i+16])+',' for i in range(0,len(pixels),16))
        source.append('};')
        entries.append('{'+f'{w},{h},{symbol}'+'}')
    source.append('static const '+image_type+' '+table+'['+str(count)+'][2]={')
    source.extend('{'+','.join(entries[i:i+2])+'},' for i in range(0,len(entries),2))
    source.append('};')
    args.output.parent.mkdir(parents=True,exist_ok=True)
    args.output.write_text('\n'.join(source)+'\n')
    print(f'classic-art: verified and decoded {len(entries)} pinned XPMs')

if __name__=='__main__': main()
